### PR TITLE
Fix timer kill key error

### LINKED ISSUE #82: Console Error
```16:40:02 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'CounterStrikeSharp.API.Core.CCSPlayerController' was not present in the dictionary.
   at RetakesAllocator.Menus.GunsMenu.OnMenuTimeout(CCSPlayerController player) in /home/runner/work/cs2-retakes-allocator/cs2-retakes-allocator/RetakesAllocator/Menus/GunsMenu.cs:line 33
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

### PR DESCRIPTION
**Pull request by yonilerner**
Closes #82

### CODE REVIEW

File: RetakesAllocator/Menus/GunsMenu.cs [hunk 1]
```diff
@@ -30,7 +30,10 @@ private void OnMenuTimeout(CCSPlayerController player)
         player.PrintToChat($"{MessagePrefix}You did not interact with the menu in {MenuTimeout} seconds!");
 
         PlayersInMenu.Remove(player);
-        _menuTimeoutTimers[player].Kill();
+        if (_menuTimeoutTimers.TryGetValue(player, out var playerTimer))
+        {
+            playerTimer.Kill();
+        }
         _menuTimeoutTimers.Remove(player);
```
Comment (B3none) [inline RetakesAllocator/Menus/GunsMenu.cs:37]: Might be worth doing this in the if statement above

File: RetakesAllocator/Menus/GunsMenu.cs [hunk 2]
```diff
@@ -51,7 +54,10 @@ private void OnMenuComplete(CCSPlayerController player)
         player.PrintToChat($"{MessagePrefix}The weapons you have selected will be given to you at the start of the next round!");
 
         PlayersInMenu.Remove(player);
-        _menuTimeoutTimers[player].Kill();
+        if (_menuTimeoutTimers.TryGetValue(player, out var playerTimer))
+        {
+            playerTimer.Kill();
+        }
         _menuTimeoutTimers.Remove(player);
```
Comment (B3none) [inline RetakesAllocator/Menus/GunsMenu.cs:61]: Might be worth doing this in the if statement above too

**Review by B3none — CHANGES_REQUESTED** [review]

File: RetakesAllocator/Menus/GunsMenu.cs (hunk 1 above)
Comment (yonilerner) [reply RetakesAllocator/Menus/GunsMenu.cs]: went a slightly different direction
